### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by yessymarie** [bimdata/BIMDataToPowerBI#5]
How can i know where is the dataset for the pie chart?
Thank you

**Comment by benjaminaudet** [comment]
When you use PowerBI with Python, the variable `dataset` is a global variable accessible in the Python script context.

**Comment by Amoki** [comment]
This project is currently in alpha. A new version with improved documentation will come soon.
Anyway, all the data come from BIMData API and are dynamic. They're fetched on startup from BIMData
